[package]
name = "alo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argmin = "0.10.0"
statrs = "0.17.1"
time = { version = "0.3.36", features = ["macros"] }

[dev-dependencies]
rand = "0.8.5"
